import { useCallback, useEffect, useRef, useState, type FormEvent, type KeyboardEvent as ReactKeyboardEvent, type MutableRefObject, type ReactNode } from "react";
import { createRoot } from "react-dom/client";
import { Dialog } from "../../ui";
import { text } from "../../core/locale";
import { buildFileTree, diagnosticsForEditor, editorResponseIsCurrent, type EditorFileTreeEntry } from "./state";

type Diagnostic = { severity: string; code: string; message: string; path?: string; line?: number; column?: number };
type FileRecord = { path: string; title?: string; language: string; content: string; digest: string; diagnostics?: Diagnostic[] };
type TemplateField = { name: string; label: string; type: string; required: boolean; options?: string[] };
type Template = { key: string; label: string; languages: string[]; fields: TemplateField[] };
type CM = { getValue(): string; focus(): void; destroy(): void; setTheme(theme: string): void; gotoLine(line: number, column: number): void; setDiagnostics(items: Diagnostic[]): void };
type APIError = Error & { code?: string; details?: any };

const action = (name: string, body: unknown, method = "POST"): RequestInit => ({ method, headers: { "Content-Type": "application/json", "X-Toudocu-Action": name, Accept: "application/json" }, body: JSON.stringify(body) });

function CodeEditor({ file, diagnostics, handle, onChange }: { file: FileRecord; diagnostics: Diagnostic[]; handle: MutableRefObject<CM | null>; onChange: (value: string) => void }) {
  const host = useRef<HTMLDivElement>(null); const fallback = useRef<HTMLTextAreaElement>(null);
  useEffect(() => {
    if (!host.current) return;
    handle.current = window.ToudocuCodeMirror?.create({ parent: host.current, doc: file.content, language: file.language, onChange: () => onChange(handle.current!.getValue()) }) || null;
    if (!handle.current && fallback.current) fallback.current.value = file.content;
    const theme = (event: Event) => handle.current?.setTheme((event as CustomEvent).detail.theme);
    document.addEventListener("toudocu:themechange", theme);
    return () => { document.removeEventListener("toudocu:themechange", theme); handle.current?.destroy(); handle.current = null; host.current?.replaceChildren(); };
  }, [file.path, file.digest]);
  useEffect(() => handle.current?.setDiagnostics(diagnosticsForEditor(diagnostics, file.path)), [diagnostics, file.path]);
  return <><div ref={host} data-editor-host /><textarea ref={fallback} data-editor-fallback hidden={Boolean(window.ToudocuCodeMirror)} spellCheck={false} aria-label={text("editor.documentContent")} onInput={(event) => onChange(event.currentTarget.value)} /></>;
}

function FileTree({ entries, active, collapsed, query, onToggle, onOpen }: { entries: EditorFileTreeEntry[]; active: string; collapsed: Set<string>; query: string; onToggle: (path: string, open: boolean) => void; onOpen: (path: string) => void }): ReactNode {
  return <ul>{entries.map((entry) => entry.kind === "directory" ? <li key={entry.path}><details open={Boolean(query) || !collapsed.has(entry.path)} onToggle={(event) => !query && onToggle(entry.path, event.currentTarget.open)}><summary>{entry.name}</summary><FileTree entries={entry.children} active={active} collapsed={collapsed} query={query} onToggle={onToggle} onOpen={onOpen} /></details></li> : <li key={entry.file.path}><button type="button" data-file-path={entry.file.path} className={entry.file.path === active ? "is-active" : ""} onClick={() => onOpen(entry.file.path)}><span>{entry.name}</span>{entry.file.language !== "markdown" && <small>{entry.file.language}</small>}</button></li>)}</ul>;
}

function EditorApp() {
  const page = window.ToudocuPage; const locale = page?.ui.locale || "en"; const API = page?.runtime === "serve" && page.capabilities?.editor ? page.endpoints?.editor || "" : "";
  const [files, setFiles] = useState<FileRecord[]>([]); const filesRef = useRef<FileRecord[]>([]); const [templates, setTemplates] = useState<Template[]>([]); const revision = useRef(""); const etag = useRef("");
  const [current, setCurrent] = useState<FileRecord | null>(null); const currentRef = useRef<FileRecord | null>(null); const content = useRef(""); const [dirty, setDirtyState] = useState(false); const dirtyRef = useRef(false); const cm = useRef<CM | null>(null);
  const [external, setExternal] = useState<any>(null); const [view, setViewState] = useState("editor"); const viewRef = useRef("editor"); const [diagnostics, setDiagnostics] = useState<Diagnostic[]>([]); const [preview, setPreview] = useState(""); const [previewError, setPreviewError] = useState("");
  const [filter, setFilter] = useState(""); const [collapsed, setCollapsed] = useState(new Set<string>()); const [treeOpen, setTreeOpen] = useState(false); const [createOpen, setCreateOpen] = useState(false); const [toast, setToast] = useState<{ message: string; error: boolean } | null>(null);
  const validateGeneration = useRef(0); const previewGeneration = useRef(0); const validateTimer = useRef(0); const savingRef = useRef(false); const [saving, setSaving] = useState(false);
  const announce = (message: string, error = false) => { setToast({ message, error }); window.setTimeout(() => setToast(null), 2600); };
  const request = async (url: string, options: RequestInit = {}) => { const response = await fetch(url, { cache: "no-store", ...options }); if (response.status === 304) return { response, data: null }; const data = await response.json().catch(() => null); if (!response.ok) { const error = new Error(data?.error?.message || `HTTP ${response.status}`) as APIError; error.code = data?.error?.code; error.details = data?.error?.details; throw error; } return { response, data }; };
  const setDirty = (next: boolean) => { dirtyRef.current = next; setDirtyState(next); document.title = text("features.editor.index.002", [next ? "• " : ""]); };
  const applyFile = useCallback((file: FileRecord) => { validateGeneration.current++; previewGeneration.current++; currentRef.current = file; setCurrent(file); content.current = file.content; setDirty(false); setExternal(null); setDiagnostics(file.diagnostics || []); setPreview(""); setPreviewError(""); history.replaceState(history.state, "", `?path=${encodeURIComponent(file.path)}`); try { sessionStorage.setItem("toudocu-editor-path", file.path); } catch {} document.dispatchEvent(new CustomEvent("toudocu:editorpathchange", { detail: { path: file.path } })); }, []);
  const fetchFile = async (path: string) => (await request(`${API}/file?path=${encodeURIComponent(path)}`)).data.file as FileRecord;
  const openFile = useCallback(async (path: string) => { if (dirtyRef.current && !confirm(text("features.editor.index.007"))) return; try { applyFile(await fetchFile(path)); setTreeOpen(false); } catch (error) { announce((error as Error).message, true); } }, [API, applyFile]);
  const loadFiles = useCallback(async (conditional = false) => { const { response, data } = await request(`${API}/files`, { headers: conditional && etag.current ? { "If-None-Match": etag.current } : {} }); if (!data) return; const previous = revision.current; etag.current = response.headers.get("ETag") || ""; revision.current = data.revision; filesRef.current = data.files; setFiles(data.files); setTemplates(data.templates); const active = currentRef.current; if (previous && previous !== revision.current && active) { const fresh = data.files.find((file: FileRecord) => file.path === active.path); if (!fresh) setExternal({ removed: true }); else if (fresh.digest !== active.digest) { const latest = await fetchFile(active.path); if (dirtyRef.current) setExternal(latest); else { applyFile(latest); announce(text("features.editor.index.006")); } } } }, [API, applyFile]);
  const updatePreview = useCallback(async () => { const active = currentRef.current; if (active?.language !== "markdown") return; const generation = ++previewGeneration.current; const path = active.path; try { const { data } = await request(`${API}/preview`, action("preview", { path, content: content.current })); if (!editorResponseIsCurrent(path, currentRef.current?.path || "", generation, previewGeneration.current)) return; setPreview(data.html); setPreviewError(""); setDiagnostics(data.diagnostics || []); } catch (error) { if (generation === previewGeneration.current) { setPreview(""); setPreviewError((error as Error).message); } } }, [API]);
  const validate = useCallback(async () => { const active = currentRef.current; if (!active) return; const generation = ++validateGeneration.current; const path = active.path; try { const { data } = await request(`${API}/validate`, action("validate", { path, content: content.current })); if (!editorResponseIsCurrent(path, currentRef.current?.path || "", generation, validateGeneration.current)) return; setDiagnostics(data.diagnostics || []); if (active.language === "markdown" && viewRef.current !== "editor") void updatePreview(); } catch (error) { if (generation === validateGeneration.current) announce((error as Error).message, true); } }, [API, updatePreview]);
  const changed = (value: string) => { content.current = value; setDirty(value !== currentRef.current?.content); window.clearTimeout(validateTimer.current); validateTimer.current = window.setTimeout(validate, 320); };
  const setView = (next: string) => { if (next === "split" && matchMedia("(max-width: 720px)").matches) next = "editor"; viewRef.current = next; setViewState(next); if (next !== "editor") void updatePreview(); };
  const save = useCallback(async (overwrite = false, digest = currentRef.current?.digest) => { const active = currentRef.current; if (savingRef.current || !active || (!dirtyRef.current && !overwrite)) return; savingRef.current = true; setSaving(true); try { const { data } = await request(`${API}/file`, action("save", { path: active.path, content: content.current, expectedDigest: digest, confirmOverwrite: overwrite }, "PUT")); revision.current = data.revision; applyFile(data.file); announce(text("features.editor.index.009")); await loadFiles(); } catch (error) { const failure = error as APIError; if (failure.code === "stale_digest") { setExternal({ ...failure.details, path: active.path, language: active.language }); announce(text("features.editor.index.010"), true); } else announce(failure.message, true); } finally { savingRef.current = false; setSaving(false); } }, [API, applyFile, loadFiles]);

  useEffect(() => { if (!API) return; void loadFiles().then(async () => { const path = new URLSearchParams(location.search).get("path"); const first = filesRef.current.find((file) => file.path === path) || filesRef.current[0]; if (first) await openFile(first.path); }).catch((error) => announce(error.message, true)); const timer = window.setInterval(() => void loadFiles(true).catch(() => {}), 2000); return () => { clearInterval(timer); clearTimeout(validateTimer.current); }; }, [API]);
  useEffect(() => { const key = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLocaleLowerCase(locale) === "s") { event.preventDefault(); void save(); } }; document.addEventListener("keydown", key); const unload = (event: BeforeUnloadEvent) => { if (dirtyRef.current) { event.preventDefault(); event.returnValue = ""; } }; addEventListener("beforeunload", unload); const media = matchMedia("(max-width: 720px)"); const resize = () => media.matches && viewRef.current === "split" && setView("editor"); media.addEventListener("change", resize); return () => { document.removeEventListener("keydown", key); removeEventListener("beforeunload", unload); media.removeEventListener("change", resize); }; }, [locale, save]);
  useEffect(() => { if (!treeOpen) return; const key = (event: KeyboardEvent) => { if (event.key === "Escape") { setTreeOpen(false); document.querySelector<HTMLButtonElement>("[data-tree-toggle]")?.focus(); } }; document.addEventListener("keydown", key); return () => document.removeEventListener("keydown", key); }, [treeOpen]);
  if (!API) return <main id="editor-workspace" className="editor-workspace"><div data-ui-state="capability-unavailable">{text("features.editor.index.001")}</div></main>;
  const visible = files.filter((file) => `${file.path} ${file.title || ""}`.toLocaleLowerCase(locale).includes(filter.trim().toLocaleLowerCase(locale)));
  return <><EditorToolbar API={API} current={current} dirty={dirty} saving={saving} onTree={() => setTreeOpen(true)} onCreate={() => setCreateOpen(true)} onSave={() => void save()} /><div className="editor-layout"><aside className={`editor-tree${treeOpen ? " is-open" : ""}`} data-tree><div className="tree-heading"><strong>{text("editor.documents")}</strong><button type="button" data-tree-close aria-label={text("editor.closeTree")} onClick={() => { setTreeOpen(false); document.querySelector<HTMLButtonElement>("[data-tree-toggle]")?.focus(); }}>{text("editor.close")}</button></div><label className="tree-search"><span>{text("editor.filter")}</span><input type="search" data-file-filter placeholder={text("editor.pathOrTitle")} value={filter} onChange={(event) => setFilter(event.target.value)} /></label><nav aria-label={text("editor.sourceFiles")} data-file-tree><FileTree entries={buildFileTree(visible)} active={current?.path || ""} collapsed={collapsed} query={filter} onToggle={(path, open) => setCollapsed((prior) => { const next = new Set(prior); open ? next.delete(path) : next.add(path); return next; })} onOpen={(path) => void openFile(path)} /></nav></aside><main id="editor-workspace" className="editor-workspace"><Conflict external={external} dirty={dirty} current={current} content={() => content.current} onLoad={() => { applyFile({ ...current!, ...external, diagnostics: [] }); announce(text("features.editor.index.014")); }} onOverwrite={() => void save(true, external?.digest)} /><ViewTabs view={view} markdown={current?.language === "markdown"} onView={setView} /><div className="editor-stage" data-stage={view}><section className="source-pane" aria-label={text("editor.sourcePane")}>{current && <CodeEditor file={current} diagnostics={diagnostics} handle={cm} onChange={changed} />}</section><section className="preview-pane" aria-label={text("editor.preview")} data-preview>{preview ? <article className="preview-document" dangerouslySetInnerHTML={{ __html: preview }} /> : <div className="preview-empty" data-ui-state={previewError ? "error" : "empty"}>{previewError || text("editor.previewMarkdown")}</div>}</section></div><Diagnostics items={diagnostics} current={current} onOpen={openFile} onGoto={(line, column) => cm.current?.gotoLine(line, column)} /></main></div><CreateDialog open={createOpen} templates={templates} API={API} request={request} onClose={() => setCreateOpen(false)} onCreated={async (data) => { revision.current = data.revision; await loadFiles(); applyFile(data.file); setCreateOpen(false); announce(text("features.editor.index.012")); }} /><div className={`editor-toast${toast ? " is-visible" : ""}${toast?.error ? " is-error" : ""}`} data-toast role="status" aria-live="polite">{toast?.message}</div></>;
}

function EditorToolbar({ API, current, dirty, saving, onTree, onCreate, onSave }: { API: string; current: FileRecord | null; dirty: boolean; saving: boolean; onTree: () => void; onCreate: () => void; onSave: () => void }) {
  return <section className="workspace-context editor-context" aria-label={text("editor.actions")}><div className="editor-path"><button type="button" data-tree-toggle aria-label={text("editor.openTree")} onClick={onTree}><span aria-hidden>☰</span><span>{text("editor.files")}</span></button><span data-current-path>{current?.path || text("editor.choose")}</span><span className="dirty-mark" data-dirty-state hidden={!dirty}>{text("editor.modified")}</span></div><div className="editor-actions"><a data-raw-link href={current ? `${API}/file?raw=1&path=${encodeURIComponent(current.path)}` : "#"} target="_blank" rel="noopener" hidden={!current}>{text("editor.source")}</a><button type="button" data-create-open onClick={onCreate}>{text("editor.create")}</button><button className="primary" type="button" data-save disabled={!current || !dirty || saving} onClick={onSave}>{text("editor.save")}</button></div></section>;
}

function ViewTabs({ view, markdown, onView }: { view: string; markdown: boolean; onView: (view: string) => void }) {
  const values = [["editor", text("editor.editor")], ["preview", text("editor.preview")], ["split", text("editor.split")]];
  const key = (event: ReactKeyboardEvent<HTMLButtonElement>, index: number) => { const tabs = [...document.querySelectorAll<HTMLButtonElement>("[data-view]")]; let next = index; if (event.key === "ArrowRight") next = (index + 1) % tabs.length; else if (event.key === "ArrowLeft") next = (index - 1 + tabs.length) % tabs.length; else if (event.key === "Home") next = 0; else if (event.key === "End") next = tabs.length - 1; else return; while (tabs[next].disabled && next !== index) next = (next + (event.key === "ArrowLeft" ? -1 : 1) + tabs.length) % tabs.length; event.preventDefault(); tabs[next].focus(); onView(tabs[next].dataset.view!); };
  return <div className="editor-tabs" role="tablist" aria-label={text("editor.viewMode")}>{values.map(([name, label], index) => <button key={name} role="tab" aria-selected={view === name} data-view={name} disabled={name !== "editor" && !markdown} onClick={() => onView(name)} onKeyDown={(event) => key(event, index)}>{label}</button>)}</div>;
}

function Conflict({ external, dirty, current, content, onLoad, onOverwrite }: { external: any; dirty: boolean; current: FileRecord | null; content: () => string; onLoad: () => void; onOverwrite: () => void }) {
  if (!external) return null;
  const download = () => { const url = URL.createObjectURL(new Blob([content()], { type: "text/plain;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `${current?.path.split("/").pop()}.unsaved`; link.click(); URL.revokeObjectURL(url); };
  return <div className="editor-notice" data-conflict role="alert"><strong>{text("editor.externalTitle")}</strong><span data-conflict-message>{text(external.removed ? "features.editor.index.004" : "features.editor.index.005")}</span>{external.removed ? <button type="button" data-conflict-download onClick={download}>{text("editor.download")}</button> : <><button type="button" data-conflict-load onClick={() => (!dirty || confirm(text("features.editor.index.013"))) && onLoad()}>{text("editor.loadExternal")}</button><button type="button" data-conflict-overwrite onClick={onOverwrite}>{text("editor.overwrite")}</button></>}</div>;
}

function Diagnostics({ items, current, onOpen, onGoto }: { items: Diagnostic[]; current: FileRecord | null; onOpen: (path: string) => void; onGoto: (line: number, column: number) => void }) {
  const severity = (value: string) => value === "error" ? text("health.error") : value === "warning" ? text("health.warning") : value;
  return <section className="diagnostics" aria-labelledby="diagnostics-title"><div className="diagnostics-heading"><strong id="diagnostics-title">{text("editor.diagnostics")}</strong><span data-diagnostic-count>{items.length}</span></div><ol data-diagnostics>{items.map((item, index) => <li key={`${item.code}-${index}`}><button type="button" className={`diagnostic-${item.severity}`} onClick={() => item.path && item.path !== current?.path ? onOpen(item.path) : onGoto(item.line || 1, item.column || 1)}><strong><span className="diagnostic-severity">{severity(item.severity)} · </span>{item.code}</strong><span>{item.message}</span><small>{item.path || current?.path}{item.line ? `:${item.line}:${item.column || 1}` : ""}</small></button></li>)}</ol></section>;
}

function CreateDialog({ open, templates, API, request, onClose, onCreated }: { open: boolean; templates: Template[]; API: string; request: (url: string, options?: RequestInit) => Promise<any>; onClose: () => void; onCreated: (data: any) => Promise<void> }) {
  const [key, setKey] = useState(""); const template = templates.find((item) => item.key === key) || templates[0]; const [language, setLanguage] = useState(""); const [values, setValues] = useState<Record<string, string>>({}); const [error, setError] = useState("");
  useEffect(() => { if (open && templates[0]) { setKey(templates[0].key); setLanguage(templates[0].languages[0] || ""); setValues({}); setError(""); } }, [open, templates]);
  useEffect(() => { if (template && !template.languages.includes(language)) setLanguage(template.languages[0] || ""); }, [template, language]);
  useEffect(() => { if (template) setValues(Object.fromEntries(template.fields.map((field) => [field.name, field.type === "select" ? field.options?.[0] || "" : ""]))); }, [template?.key]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!template) return; try { await onCreated((await request(`${API}/create`, action("create", { template: template.key, language, fields: values }))).data); } catch (failure) { setError((failure as Error).message); } };
  return <Dialog.Root open={open} onOpenChange={(next) => !next && onClose()}><Dialog.Portal><Dialog.Backdrop className="ui-backdrop" /><Dialog.Viewport className="ui-dialog-viewport"><Dialog.Popup className="ui-dialog" data-create-dialog><form data-create-form onSubmit={submit}><header><Dialog.Title>{text("editor.createDocument")}</Dialog.Title><Dialog.Close aria-label={text("editor.close")}>{text("editor.close")}</Dialog.Close></header><label>{text("editor.template")}<select data-template-select value={template?.key || ""} onChange={(event) => setKey(event.target.value)}>{templates.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label><label>{text("editor.language")}<select data-template-language value={language} onChange={(event) => setLanguage(event.target.value)}>{template?.languages.map((item) => <option key={item} value={item}>{item.toUpperCase()}</option>)}</select></label><div data-template-fields>{template?.fields.map((field) => <label key={field.name}>{field.label}{field.type === "select" ? <select required={field.required} value={values[field.name] || ""} onChange={(event) => setValues({ ...values, [field.name]: event.target.value })}>{field.options?.map((option) => <option key={option} value={option}>{option}</option>)}</select> : <input required={field.required} value={values[field.name] || ""} onChange={(event) => setValues({ ...values, [field.name]: event.target.value })} />}</label>)}</div><p className="form-error" data-create-error role="alert">{error}</p><footer><Dialog.Close>{text("editor.cancel")}</Dialog.Close><button className="primary" type="submit">{text("editor.create")}</button></footer></form></Dialog.Popup></Dialog.Viewport></Dialog.Portal></Dialog.Root>;
}

const root = document.querySelector<HTMLElement>("[data-editor-root]");
if (root) createRoot(root).render(<EditorApp />);
